             
             #CONSONANTS
             ('tch','','','tS'),
             ('ch','','','(tS|x)'),
             ('ck','','','k'),
             ('cc','','[iey]','ks'),#success,accent
             ('c','','c',''),
             ('c','','[iey]','s'),#circle
             ('c','','','k'),#candy
             ('gh','^','','g'),#ghost
             ('gh','','','(g|f|w)'),#burgh|tough|bough
             ('gn','','','(gn|n)'),
             ('g','','[iey]','(g|dZ)'),#get,gem,giant,gigabyte
             #('th','','','(6|8|t)'),
             ('th','','','t'),
             ('kh','','','x'),
             ('ph','','','f'),
             ('sch','','','(S|sk)'),
             ('sh','','','S'),
             ('who','^','','hu'),
             ('wh','^','','w'),
             
             ('h','','$',''),#hardtofindanexamplethatisn'tinaname
             ('h','','[^aeiou]',''),#hardtofindanexamplethatisn'tinaname
             ('h','^','','H'),
             ('h','','','h'),
             
             ('j','','','dZ'),
             ('kn','^','','n'),#knight
             ('mb','','$','m'),
             ('ng','','$','(N|ng)'),
             ('pn','^','','(pn|n)'),
             ('ps','^','','(ps|s)'),
             ('qu','','','kw'),
             ('q','','','k'),
             ('tia','','','(So|Sa)'),
             ('tio','','','So'),
             ('wr','^','','r'),
             ('w','','','(w|v)'),#thevariant'v'isforspellingscomingfromGerman/Polish
             ('x','^','','z'),
             ('x','','','ks'),
             
             #VOWELS
             ('y','^','','j'),
             ('y','^','[aeiouy]','j'),
             ('yi','^','','i'),
             ('aue','','','aue'),
             ('oue','','','(aue|oue)'),
             ('ai','','','(aj|e)'),#rain|said
             ('ay','','','aj'),
             ('a','','[^aeiou]e','aj'),#plane(actually'ej')
             ('a','','','(e|o|a)'),#hat|call|part
             ('ei','','','(aj|i)'),#weigh|receive
             ('ey','','','(aj|i)'),#hey|barley
             ('ear','','','ia'),#tear
             ('ea','','','(i|e)'),#reason|treasure
             ('ee','','','i'),#between
             ('e','','[^aeiou]e','i'),#meter
             ('e','','$','(|E)'),#blame,badge
             ('e','','','E'),#bed
             ('ie','','','i'),#believe
             ('i','','[^aeiou]e','aj'),#five
             ('i','','','I'),#hit--Morsedisagrees,feelsitshouldgotoI
             ('oa','','','ou'),#toad
             ('oi','','','oj'),#join
             ('oo','','','u'),#food
             ('ou','','','(u|ou)'),#through|tough|could
             ('oy','','','oj'),#boy
             ('o','','[^aeiou]e','ou'),#rode
             ('o','','','(o|a)'),#hot--Morsedisagrees,feelsitshouldgoto9
             ('u','','[^aeiou]e','(ju|u)'),#cute|flute
             ('u','','r','(e|u)'),#turn--Morsedisagrees,feelsitshouldgotoE
             ('u','','','(u|a)'),#put
             ('y','','','i'),
             
             #TRIVIAL
             ('b','','','b'),
             ('d','','','d'),
             ('f','','','f'),
             ('g','','','g'),
             ('k','','','k'),
             ('l','','','l'),
             ('m','','','m'),
             ('n','','','n'),
             ('p','','','p'),
             ('r','','','r'),
             ('s','','','s'),
             ('t','','','t'),
             ('v','','','v'),
             ('z','','','z'),
             
             ('rulesenglish')
             
